=== Idrinth/config-check/src/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "https://raw.githubusercontent.com/Idrinth/config-check/master/src/schema.json",
    "description": "This is the configuration for the configuration check.",
    "type": "object",
    "properties": {
        "ini": {
            "$ref": "#ext"
        },
        "yaml": {
            "$ref": "#ext"
        },
        "xml": {
            "$ref": "#ext"
        },
        "json": {
            "$ref": "#ext"
        },
        "blacklist": {
            "$ref": "#blacklist"
        },
        "verbosity": {
            "type": "integer",
            "minimum": 0,
            "maximum": 3,
            "description": "A value from 0-3 that defines how much information is printed out."
        },
        "warningAsError": {
            "type": "boolean",
            "description": "Consider all warnings to be errors."
        }
    },
    "additionalProperties": false,
    "definitions": {
        "blacklist": {
            "$id": "#blacklist",
            "type": "array",
            "description": "files and folders to ignore",
            "items": {
                "type": "string",
                "pattern": "^[^\\\\]+$"
            }
        },
        "ext": {
            "$id": "#ext",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "validity": {
                    "type": "boolean",
                    "description": "should files be checked for basic syntax and parseability"
                },
                "mapping": {
                    "type": "object",
                    "description": "a filename to schema-source mapping",
                    "patternProperties": {
                        "^([^\\/]+)+$": {
                            "type": "string",
                            "format": "uri"
                        }
                    }
                },
                "blacklist": {
                    "$ref": "#blacklist"
                }
            },
            "required": ["validity"]
        }
    }
}

=== Idrinth/config-check/.idrinth-cc.json
{
    "verbosity": 2,
    "blacklist": ["/vendor", "/test"],
    "xml": {
        "validity": true
    },
    "ini": {
        "validity": false
    },
    "json": {
        "validity": true,
        "mapping": {
            ".idrinth-cc.json": "cwd://src/schema.json",
            "composer.json": "https://getcomposer.org/schema.json"
        },
        "blacklist": ["broken.json"],
        "additional-extensions": ["lock"]
    },
    "yaml": {
        "validity": true,
        "mapping": {
            ".travis.yml": "https://raw.githubusercontent.com/travis-ci/travis-yml/master/schema.json"
        },
        "additional-extensions": ["yml", "neon"]
    }
}
